<?php

namespace ContainerWTeRtbA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PK7mt3BService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.pK7mt3B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pK7mt3B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objTinyUrl' => ['privates', 'App\\Service\\TinyUrl', 'getTinyUrlService', true],
        ], [
            'objTinyUrl' => 'App\\Service\\TinyUrl',
        ]);
    }
}
