<?php

namespace ContainerWnur2Hw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTinyUrlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TinyUrl' shared autowired service.
     *
     * @return \App\Service\TinyUrl
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TinyUrl.php';

        return $container->privates['App\\Service\\TinyUrl'] = new \App\Service\TinyUrl();
    }
}
