<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5s7tgM\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5s7tgM/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJ5s7tgM.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJ5s7tgM\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJ5s7tgM\App_KernelTestDebugContainer([
    'container.build_hash' => 'J5s7tgM',
    'container.build_id' => '48c2f539',
    'container.build_time' => 1686146201,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5s7tgM');
