<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnur2Hw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnur2Hw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWnur2Hw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWnur2Hw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWnur2Hw\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wnur2Hw',
    'container.build_id' => '6f539556',
    'container.build_time' => 1686062326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnur2Hw');
